### ISSUE TITLE
Ability to run it via arguments

### ISSUE THREAD

**Issue by 0x2b00b1e5** [springkim/FSpring#1]
It would be a nice feature to run the program with arguments.

So like ```./`FSpring --extract_frames -f "/home/user/whateverpathyouwant"```

Also: which function is doing the frame extraction? I can't seem to find it.

**Comment by springkim** [comment]
hi @hugopilot .
Thanks for good suggestion!. 

You can check frame extraction function in [here](https://github.com/springkim/FSpring/blob/master/FSpring(ubuntu)/main.cpp) line 179.

**Comment by hugopilot** [comment]
Thanks for replying! I found it.
